INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10001, 'USD', 'TL', 10, '');
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10002, 'USD', 'EUR', 2, '');
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10003, 'USD', 'AUD', 3, '');
