USE SPRINGMVCTUTORIAL

CREATE TABLE instructor_detail(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	YOUTUBE_CHANNEL VARCHAR(128) DEFAULT NULL
);

CREATE TABLE instructor(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NAME VARCHAR(45) DEFAULT NULL,
	EMAIL VARCHAR(45) DEFAULT NULL,
	INSTRUCTOR_DETAIL_ID INT FOREIGN KEY REFERENCES instructor_detail(ID)
);
