use [SPRINGMVCTUTORIAL];

CREATE TABLE instructor_detail (
  [ID] int NOT NULL IDENTITY,
  [YOUTUBE_CHANNEL] varchar(128) DEFAULT NULL,
  PRIMARY KEY ([ID])
);

CREATE TABLE instructor (
  [ID] int NOT NULL IDENTITY,
  [NAME] varchar(45) DEFAULT NULL,
  [EMAIL] varchar(45) DEFAULT NULL,
  [INSTRUCTOR_DETAIL_ID] int DEFAULT NULL,
  PRIMARY KEY ([ID]),
  CONSTRAINT [FK_DETAIL] FOREIGN KEY ([INSTRUCTOR_DETAIL_ID]) 
  REFERENCES instructor_detail([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX [FK_DETAIL_idx] ON instructor ([INSTRUCTOR_DETAIL_ID]);

CREATE TABLE course (
  [ID] int NOT NULL IDENTITY,
  [TITLE] varchar(128) DEFAULT NULL,
  [INSTRUCTOR_ID] int DEFAULT NULL,
  
  PRIMARY KEY ([ID]),
  
  CONSTRAINT [TITLE_UNIQUE] UNIQUE  ([title]),
  
  CONSTRAINT [FK_INSTRUCTOR] 
  FOREIGN KEY ([INSTRUCTOR_ID]) 
  REFERENCES instructor([ID]) 
  
  ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX [FK_INSTRUCTOR_idx] ON course ([INSTRUCTOR_ID]);
